# Generated by Django 3.0.3 on 2020-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200215_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
